/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Automata2017.Apuntador;
import Automata2017.Estandar;
import Automata2017.Maquina;
import java.awt.Color;
import java.util.Observable;
import java.util.Observer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vista.PanelPrincipal;

/**
 *
 * @author ns
 */
public class vista extends javax.swing.JDialog implements Observer, Estandar {

    /**
     * Creates new form vista
     */
    String cadena;

    Maquina maquinita;

    public vista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNum1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNum2 = new javax.swing.JTextField();
        jButtonProcesar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCintaVisual = new javax.swing.JTable();
        jLabelResultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Maquina de Turing");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Maquina de Turing"));

        jLabel1.setText("Número 1: ");

        jTextFieldNum1.setBackground(new java.awt.Color(149, 147, 147));
        jTextFieldNum1.setText("1111");

        jLabel2.setText("Número 2: ");

        jTextFieldNum2.setBackground(new java.awt.Color(149, 147, 147));
        jTextFieldNum2.setText("0010");
        jTextFieldNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNum2ActionPerformed(evt);
            }
        });

        jButtonProcesar.setText("Procesar");
        jButtonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcesarActionPerformed(evt);
            }
        });

        jTableCintaVisual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "", "Apuntador", "Original"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableCintaVisual);

        jLabel3.setText("Resultado :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButtonProcesar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesarActionPerformed
        // TODO add your handling code here:

        jLabelResultado.setText("");
        // Validamos que los número sean binarios mediante la siguiente ER
        Pattern a = Pattern.compile("0|(1|0)(1|0){1,}");
        Matcher binario1Validar = a.matcher(jTextFieldNum1.getText());
        Matcher binario2Validar = a.matcher(jTextFieldNum2.getText());

        if (binario1Validar.matches() && binario2Validar.matches()) {

            // Se valida que los número tenga la misma longitud, debido a que maquina solo procesa cuando son de igual longitud
            if (jTextFieldNum2.getText().length() != jTextFieldNum1.getText().length()) {
                int dif = jTextFieldNum2.getText().length() - jTextFieldNum1.getText().length();

                // Cuando se tiene dos números longitude distintas se llena con ceros a la izquiera para equilibrar
                String complemento = "";
                for (int i = 0; i < Math.abs(dif); i++) {
                    complemento += "0";
                }
                if (dif > 0) {

                    jTextFieldNum1.setText(complemento + jTextFieldNum1.getText());
                } else {

                    jTextFieldNum2.setText(complemento + jTextFieldNum2.getText());
                }

            }

            // La estructura de la cinta es LINUMEROINUMERO2IL
            cadena = CARACTERVACIO + CARACTERINTERMEDIO + jTextFieldNum1.getText() + CARACTERINTERMEDIO + jTextFieldNum2.getText() + CARACTERINTERMEDIO + CARACTERVACIO;

            Thread trabajador = new Thread() {
                @Override
                public void run() {
                    maquinita = new Maquina(cadena);
                    Apuntador referencia = new Apuntador(1);
                    referencia.addObserver(vista.this);
                    jLabelResultado.setText(maquinita.toWork(referencia));

                }

            };

            trabajador.start();
        } else {
            JOptionPane.showMessageDialog(this, "Recuerde que debe escribir números binarios en los campos");
        }

//        //010
//        //011
//        //101
//        

    }//GEN-LAST:event_jButtonProcesarActionPerformed

    private void jTextFieldNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNum2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldNum2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonProcesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCintaVisual;
    private javax.swing.JTextField jTextFieldNum1;
    private javax.swing.JTextField jTextFieldNum2;
    // End of variables declaration//GEN-END:variables

    @Override
    @SuppressWarnings("empty-statement")
    public void update(Observable o, Object arg) {

        Apuntador apuntador = (Apuntador) arg;

        DefaultTableModel model = (DefaultTableModel) jTableCintaVisual.getModel();
        for (; model.getRowCount() > 0;) {
            model.removeRow(0);
        }

        for (int i = 0; i < cadena.length(); i++) {

            if (apuntador.getReferencia() != i) {
                String[] datos = {maquinita.getCinta().get(i), " ", String.valueOf(cadena.charAt(i))};
                model.addRow(datos);
            } else {
                String[] datos = {maquinita.getCinta().get(i), "<", String.valueOf(cadena.charAt(i))};
                model.addRow(datos);
            }

        }//

    }

}
